name: save
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  image_picker: ^1.0.4
  firebase_storage: ^11.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/photos/
    - assets/icons/
    - assets/logo/
    - assets/eye/
    - assets/leg/
    - assets/background/